# Complete Chinese item name mapping from Minecraft Wiki (Bedrock Edition, non-education)
_ITEM_CN: dict[str, str] = {
    # === 食物 ===
    "golden_apple": "金苹果", "enchanted_golden_apple": "附魔金苹果",
    "mushroom_stew": "蘑菇煲", "bread": "面包",
    "porkchop": "生猪排", "cooked_porkchop": "熟猪排",
    "cod": "生鳕鱼", "salmon": "生鲑鱼", "tropical_fish": "热带鱼", "pufferfish": "河豚",
    "cooked_cod": "熟鳕鱼", "cooked_salmon": "熟鲑鱼",
    "dried_kelp": "干海带", "cookie": "曲奇", "melon_slice": "西瓜",
    "beef": "生牛肉", "cooked_beef": "牛排",
    "chicken": "生鸡肉", "cooked_chicken": "熟鸡肉",
    "rotten_flesh": "腐肉", "spider_eye": "蜘蛛眼",
    "carrot": "胡萝卜", "potato": "马铃薯",
    "baked_potato": "烤马铃薯", "poisonous_potato": "毒马铃薯",
    "golden_carrot": "金胡萝卜", "pumpkin_pie": "南瓜派",
    "beetroot": "甜菜根", "beetroot_soup": "甜菜汤", "sweet_berries": "甜浆果",
    "rabbit": "生兔肉", "cooked_rabbit": "熟兔肉", "rabbit_stew": "兔肉煲",
    "mutton": "生羊肉", "cooked_mutton": "熟羊肉",
    "chorus_fruit": "紫颂果", "popped_chorus_fruit": "爆裂紫颂果",
    "suspicious_stew": "谜之炖菜", "honey_bottle": "蜂蜜瓶",
    "cake": "蛋糕", "glistering_melon_slice": "闪烁的西瓜片",
    # === 材料/矿物 ===
    "coal": "煤炭", "charcoal": "木炭", "diamond": "钻石", "emerald": "绿宝石",
    "iron_ingot": "铁锭", "gold_ingot": "金锭", "copper_ingot": "铜锭",
    "netherite_ingot": "下界合金锭", "netherite_scrap": "下界合金碎片",
    "raw_iron": "粗铁", "raw_gold": "粗金", "raw_copper": "粗铜",
    "iron_nugget": "铁粒", "gold_nugget": "金粒",
    "nether_star": "下界之星", "stick": "木棍", "bowl": "碗",
    "redstone": "红石粉", "glowstone_dust": "荧石粉", "gunpowder": "火药",
    "quartz": "下界石英", "netherbrick": "下界砖", "brick": "红砖",
    "clay_ball": "黏土", "prismarine_shard": "海晶碎片", "prismarine_crystals": "海晶砂粒",
    "lapis_lazuli": "青金石", "flint": "燧石", "leather": "皮革",
    "rabbit_hide": "兔子皮", "rabbit_foot": "兔子脚",
    "bone": "骨头", "bone_meal": "骨粉", "string": "线", "feather": "羽毛",
    "slime_ball": "黏液球", "ink_sac": "墨囊", "glow_ink_sac": "荧光墨囊",
    "blaze_rod": "烈焰棒", "blaze_powder": "烈焰粉",
    "ender_pearl": "末影珍珠", "ender_eye": "末影之眼",
    "ghast_tear": "恶魂之泪", "magma_cream": "岩浆膏",
    "fermented_spider_eye": "发酵蛛眼", "dragon_breath": "龙息",
    "shulker_shell": "潜影壳", "heart_of_the_sea": "海洋之心",
    "nautilus_shell": "鹦鹉螺壳", "scute": "海龟鳞甲", "armadillo_scute": "犰狳鳞甲",
    "phantom_membrane": "幻翼膜", "honeycomb": "蜜脾", "nether_wart": "下界疣",
    "paper": "纸", "book": "书", "sugar": "糖", "egg": "鸡蛋",
    "wheat": "小麦", "cocoa_beans": "可可豆",
    "kelp": "海带", "sugar_cane": "甘蔗", "amethyst_shard": "紫水晶碎片",
    "echo_shard": "回响碎片", "resin_brick": "树脂砖",
    "disc_fragment_5": "唱片残片（5）",
    "nether_sprouts": "下界苗",
    # === 工具 ===
    "wooden_sword": "木剑", "stone_sword": "石剑", "iron_sword": "铁剑",
    "golden_sword": "金剑", "diamond_sword": "钻石剑", "netherite_sword": "下界合金剑",
    "wooden_shovel": "木锹", "stone_shovel": "石锹", "iron_shovel": "铁锹",
    "golden_shovel": "金锹", "diamond_shovel": "钻石锹", "netherite_shovel": "下界合金锹",
    "wooden_pickaxe": "木镐", "stone_pickaxe": "石镐", "iron_pickaxe": "铁镐",
    "golden_pickaxe": "金镐", "diamond_pickaxe": "钻石镐", "netherite_pickaxe": "下界合金镐",
    "wooden_axe": "木斧", "stone_axe": "石斧", "iron_axe": "铁斧",
    "golden_axe": "金斧", "diamond_axe": "钻石斧", "netherite_axe": "下界合金斧",
    "wooden_hoe": "木锄", "stone_hoe": "石锄", "iron_hoe": "铁锄",
    "golden_hoe": "金锄", "diamond_hoe": "钻石锄", "netherite_hoe": "下界合金锄",
    "mace": "重锤", "trident": "三叉戟", "shield": "盾牌",
    "bow": "弓", "crossbow": "弩", "arrow": "箭",
    "flint_and_steel": "打火石", "fishing_rod": "钓鱼竿",
    "carrot_on_a_stick": "胡萝卜钓竿", "warped_fungus_on_a_stick": "诡异菌钓竿",
    "shears": "剪刀", "compass": "指南针", "recovery_compass": "追溯指针",
    "clock": "时钟", "lodestone_compass": "磁石指针", "spyglass": "望远镜",
    "brush": "刷子", "goat_horn": "山羊角",
    "fire_charge": "火焰弹", "firework_rocket": "烟花火箭", "firework_star": "烟火之星",
    # === 盔甲 ===
    "leather_helmet": "皮革帽子", "leather_chestplate": "皮革外套",
    "leather_leggings": "皮革裤子", "leather_boots": "皮革靴子",
    "chainmail_helmet": "锁链头盔", "chainmail_chestplate": "锁链胸甲",
    "chainmail_leggings": "锁链护腿", "chainmail_boots": "锁链靴子",
    "iron_helmet": "铁头盔", "iron_chestplate": "铁胸甲",
    "iron_leggings": "铁护腿", "iron_boots": "铁靴子",
    "golden_helmet": "金头盔", "golden_chestplate": "金胸甲",
    "golden_leggings": "金护腿", "golden_boots": "金靴子",
    "diamond_helmet": "钻石头盔", "diamond_chestplate": "钻石胸甲",
    "diamond_leggings": "钻石护腿", "diamond_boots": "钻石靴子",
    "netherite_helmet": "下界合金头盔", "netherite_chestplate": "下界合金胸甲",
    "netherite_leggings": "下界合金护腿", "netherite_boots": "下界合金靴子",
    "turtle_helmet": "海龟壳", "wolf_armor": "狼铠",
    "leather_horse_armor": "皮革马铠", "iron_horse_armor": "铁马铠",
    "gold_horse_armor": "金马铠", "diamond_horse_armor": "钻石马铠",
    # === 桶 ===
    "bucket": "铁桶", "water_bucket": "水桶", "lava_bucket": "熔岩桶",
    "milk_bucket": "奶桶", "cod_bucket": "鳕鱼桶", "salmon_bucket": "鲑鱼桶",
    "tropical_fish_bucket": "热带鱼桶", "pufferfish_bucket": "河豚桶",
    "powder_snow_bucket": "细雪桶", "axolotl_bucket": "美西螈桶",
    "tadpole_bucket": "蝌蚪桶",
    # === 染料 ===
    "white_dye": "白色染料", "orange_dye": "橙色染料", "magenta_dye": "品红色染料",
    "light_blue_dye": "淡蓝色染料", "yellow_dye": "黄色染料", "lime_dye": "黄绿色染料",
    "pink_dye": "粉红色染料", "gray_dye": "灰色染料", "light_gray_dye": "淡灰色染料",
    "cyan_dye": "青色染料", "purple_dye": "紫色染料", "blue_dye": "蓝色染料",
    "brown_dye": "棕色染料", "green_dye": "绿色染料", "red_dye": "红色染料",
    "black_dye": "黑色染料",
    # === 种子/植物 ===
    "wheat_seeds": "种子", "pumpkin_seeds": "南瓜种子", "melon_seeds": "西瓜种子",
    "beetroot_seeds": "甜菜种子", "torchflower_seeds": "火把花种子",
    "pitcher_pod": "瓶子草荚果",
    # === 交通 ===
    "saddle": "鞍", "lead": "拴绳", "name_tag": "命名牌",
    "elytra": "鞘翅", "minecart": "矿车",
    "chest_minecart": "运输矿车", "tnt_minecart": "TNT矿车",
    "hopper_minecart": "漏斗矿车", "command_block_minecart": "命令方块矿车",
    "oak_boat": "橡木船", "spruce_boat": "云杉木船", "birch_boat": "白桦木船",
    "jungle_boat": "丛林木船", "acacia_boat": "金合欢木船", "dark_oak_boat": "深色橡木船",
    "mangrove_boat": "红树木船", "cherry_boat": "樱花木船",
    "pale_oak_boat": "苍白橡木船", "bamboo_raft": "竹筏",
    "oak_chest_boat": "橡木运输船", "spruce_chest_boat": "云杉木运输船",
    "birch_chest_boat": "白桦木运输船", "jungle_chest_boat": "丛林木运输船",
    "acacia_chest_boat": "金合欢木运输船", "dark_oak_chest_boat": "深色橡木运输船",
    "mangrove_chest_boat": "红树木运输船", "cherry_chest_boat": "樱花木运输船",
    "pale_oak_chest_boat": "苍白橡木运输船", "bamboo_chest_raft": "运输竹筏",
    "chest_boat": "运输船",
    # === 药水 ===
    "potion": "药水", "splash_potion": "喷溅药水", "lingering_potion": "滞留药水",
    "glass_bottle": "玻璃瓶", "ominous_bottle": "不祥之瓶",
    "experience_bottle": "附魔之瓶", "dragon_breath": "龙息",
    # === 特殊物品 ===
    "totem_of_undying": "不死图腾", "elytra": "鞘翅",
    "writable_book": "书与笔", "written_book": "成书", "enchanted_book": "附魔书",
    "empty_map": "空地图", "filled_map": "地图",
    "armor_stand": "盔甲架", "painting": "画", "frame": "物品展示框",
    "glow_frame": "荧光物品展示框", "flower_pot": "花盆", "bed": "床",
    "snowball": "雪球", "end_crystal": "末地水晶",
    "brewing_stand": "酿造台", "cauldron": "炼药锅",
    "hopper": "漏斗", "repeater": "红石中继器", "comparator": "红石比较器",
    "skull": "生物头颅", "banner": "旗帜",
    "campfire": "营火", "soul_campfire": "灵魂营火",
    "chain": "锁链",
    "stained_hardened_clay": "带釉陶瓦",
    "blue_egg": "蓝色鸡蛋", "brown_egg": "棕色鸡蛋",
    # === 门 ===
    "wooden_door": "橡木门", "iron_door": "铁门",
    "spruce_door": "云杉木门", "birch_door": "白桦木门",
    "jungle_door": "丛林木门", "acacia_door": "金合欢木门",
    "dark_oak_door": "深色橡木门", "crimson_door": "绯红木门",
    "warped_door": "诡异木门", "mangrove_door": "红树木门",
    # === 告示牌 ===
    "oak_sign": "橡木告示牌", "spruce_sign": "云杉木告示牌",
    "birch_sign": "白桦木告示牌", "jungle_sign": "丛林木告示牌",
    "acacia_sign": "金合欢木告示牌", "dark_oak_sign": "深色橡木告示牌",
    "crimson_sign": "绯红木告示牌", "warped_sign": "诡异木告示牌",
    "mangrove_sign": "红树木告示牌", "cherry_sign": "樱花木告示牌",
    "bamboo_sign": "竹告示牌", "pale_oak_sign": "苍白橡木告示牌",
    # === 音乐唱片 ===
    "music_disc_13": "音乐唱片13", "music_disc_cat": "音乐唱片cat",
    "music_disc_blocks": "音乐唱片blocks", "music_disc_chirp": "音乐唱片chirp",
    "music_disc_far": "音乐唱片far", "music_disc_mall": "音乐唱片mall",
    "music_disc_mellohi": "音乐唱片mellohi", "music_disc_stal": "音乐唱片stal",
    "music_disc_strad": "音乐唱片strad", "music_disc_ward": "音乐唱片ward",
    "music_disc_11": "音乐唱片11", "music_disc_wait": "音乐唱片wait",
    "music_disc_pigstep": "音乐唱片Pigstep", "music_disc_otherside": "音乐唱片otherside",
    "music_disc_5": "音乐唱片5", "music_disc_relic": "音乐唱片Relic",
    # === 旗帜图案 ===
    "flower_banner_pattern": "花朵盾徽旗帜图案",
    "creeper_banner_pattern": "苦力怕盾徽旗帜图案",
    "skull_banner_pattern": "头颅盾徽旗帜图案",
    "mojang_banner_pattern": "Mojang徽标旗帜图案",
    "field_masoned_banner_pattern": "砖纹旗帜图案",
    "bordure_indented_banner_pattern": "波纹边旗帜图案",
    "piglin_banner_pattern": "猪鼻旗帜图案",
    "globe_banner_pattern": "地球旗帜图案",
    "flow_banner_pattern": "涡流旗帜图案",
    "guster_banner_pattern": "旋风旗帜图案",
    # === 陶片 ===
    "angler_pottery_sherd": "垂钓纹样陶片", "archer_pottery_sherd": "弓箭纹样陶片",
    "arms_up_pottery_sherd": "举臂纹样陶片", "blade_pottery_sherd": "利刃纹样陶片",
    "brewer_pottery_sherd": "佳酿纹样陶片", "burn_pottery_sherd": "烈焰纹样陶片",
    "danger_pottery_sherd": "危机纹样陶片", "explorer_pottery_sherd": "探险纹样陶片",
    "flow_pottery_sherd": "涡流纹样陶片", "friend_pottery_sherd": "挚友纹样陶片",
    "guster_pottery_sherd": "旋风纹样陶片", "heart_pottery_sherd": "爱心纹样陶片",
    "heartbreak_pottery_sherd": "心碎纹样陶片", "howl_pottery_sherd": "狼嚎纹样陶片",
    "miner_pottery_sherd": "采矿纹样陶片", "mourner_pottery_sherd": "悲恸纹样陶片",
    "plenty_pottery_sherd": "富饶纹样陶片", "prize_pottery_sherd": "珍宝纹样陶片",
    "scrape_pottery_sherd": "刮削纹样陶片", "sheaf_pottery_sherd": "麦捆纹样陶片",
    "shelter_pottery_sherd": "树荫纹样陶片", "skull_pottery_sherd": "头颅纹样陶片",
    "snort_pottery_sherd": "嗅探纹样陶片",
    # === 锻造模板 ===
    "netherite_upgrade_smithing_template": "下界合金升级",
    "sentry_armor_trim_smithing_template": "哨兵盔甲纹饰",
    "dune_armor_trim_smithing_template": "沙丘盔甲纹饰",
    "coast_armor_trim_smithing_template": "海岸盔甲纹饰",
    "wild_armor_trim_smithing_template": "荒野盔甲纹饰",
    "ward_armor_trim_smithing_template": "监守盔甲纹饰",
    "eye_armor_trim_smithing_template": "眼眸盔甲纹饰",
    "vex_armor_trim_smithing_template": "恼鬼盔甲纹饰",
    "tide_armor_trim_smithing_template": "潮汐盔甲纹饰",
    "snout_armor_trim_smithing_template": "猪鼻盔甲纹饰",
    "rib_armor_trim_smithing_template": "肋骨盔甲纹饰",
    "spire_armor_trim_smithing_template": "尖塔盔甲纹饰",
    "silence_armor_trim_smithing_template": "幽静盔甲纹饰",
    "wayfinder_armor_trim_smithing_template": "向导盔甲纹饰",
    "raiser_armor_trim_smithing_template": "牧民盔甲纹饰",
    "shaper_armor_trim_smithing_template": "塑造盔甲纹饰",
    "host_armor_trim_smithing_template": "雇主盔甲纹饰",
    "flow_armor_trim_smithing_template": "涡流盔甲纹饰",
    "bolt_armor_trim_smithing_template": "镶铆盔甲纹饰",
    # === 刷怪蛋(常用) ===
    "chicken_spawn_egg": "鸡刷怪蛋", "cow_spawn_egg": "牛刷怪蛋",
    "pig_spawn_egg": "猪刷怪蛋", "sheep_spawn_egg": "绵羊刷怪蛋",
    "wolf_spawn_egg": "狼刷怪蛋", "cat_spawn_egg": "猫刷怪蛋",
    "horse_spawn_egg": "马刷怪蛋", "donkey_spawn_egg": "驴刷怪蛋",
    "mule_spawn_egg": "骡刷怪蛋", "llama_spawn_egg": "羊驼刷怪蛋",
    "trader_llama_spawn_egg": "行商羊驼刷怪蛋",
    "skeleton_horse_spawn_egg": "骷髅马刷怪蛋", "zombie_horse_spawn_egg": "僵尸马刷怪蛋",
    "creeper_spawn_egg": "苦力怕刷怪蛋", "skeleton_spawn_egg": "骷髅刷怪蛋",
    "spider_spawn_egg": "蜘蛛刷怪蛋", "cave_spider_spawn_egg": "洞穴蜘蛛刷怪蛋",
    "zombie_spawn_egg": "僵尸刷怪蛋", "zombie_villager_spawn_egg": "僵尸村民刷怪蛋",
    "zombie_pigman_spawn_egg": "僵尸猪灵刷怪蛋",
    "husk_spawn_egg": "尸壳刷怪蛋", "drowned_spawn_egg": "溺尸刷怪蛋",
    "stray_spawn_egg": "流浪者刷怪蛋", "bogged_spawn_egg": "沼骸刷怪蛋",
    "wither_skeleton_spawn_egg": "凋灵骷髅刷怪蛋",
    "slime_spawn_egg": "史莱姆刷怪蛋", "magma_cube_spawn_egg": "岩浆怪刷怪蛋",
    "ghast_spawn_egg": "恶魂刷怪蛋", "blaze_spawn_egg": "烈焰人刷怪蛋",
    "enderman_spawn_egg": "末影人刷怪蛋", "endermite_spawn_egg": "末影螨刷怪蛋",
    "shulker_spawn_egg": "潜影贝刷怪蛋", "silverfish_spawn_egg": "蠹虫刷怪蛋",
    "witch_spawn_egg": "女巫刷怪蛋", "guardian_spawn_egg": "守卫者刷怪蛋",
    "elder_guardian_spawn_egg": "远古守卫者刷怪蛋",
    "villager_spawn_egg": "村民刷怪蛋", "wandering_trader_spawn_egg": "流浪商人刷怪蛋",
    "mooshroom_spawn_egg": "哞菇刷怪蛋", "bat_spawn_egg": "蝙蝠刷怪蛋",
    "squid_spawn_egg": "鱿鱼刷怪蛋", "glow_squid_spawn_egg": "发光鱿鱼刷怪蛋",
    "dolphin_spawn_egg": "海豚刷怪蛋", "turtle_spawn_egg": "海龟刷怪蛋",
    "polar_bear_spawn_egg": "北极熊刷怪蛋", "panda_spawn_egg": "熊猫刷怪蛋",
    "fox_spawn_egg": "狐狸刷怪蛋", "bee_spawn_egg": "蜜蜂刷怪蛋",
    "parrot_spawn_egg": "鹦鹉刷怪蛋", "ocelot_spawn_egg": "豹猫刷怪蛋",
    "rabbit_spawn_egg": "兔子刷怪蛋",
    "cod_spawn_egg": "鳕鱼刷怪蛋", "salmon_spawn_egg": "鲑鱼刷怪蛋",
    "pufferfish_spawn_egg": "河豚刷怪蛋", "tropical_fish_spawn_egg": "热带鱼刷怪蛋",
    "vindicator_spawn_egg": "卫道士刷怪蛋", "evoker_spawn_egg": "唤魔者刷怪蛋",
    "vex_spawn_egg": "恼鬼刷怪蛋", "pillager_spawn_egg": "掠夺者刷怪蛋",
    "ravager_spawn_egg": "劫掠兽刷怪蛋",
    "phantom_spawn_egg": "幻翼刷怪蛋", "strider_spawn_egg": "炽足兽刷怪蛋",
    "hoglin_spawn_egg": "疣猪兽刷怪蛋", "piglin_spawn_egg": "猪灵刷怪蛋",
    "piglin_brute_spawn_egg": "猪灵蛮兵刷怪蛋", "zoglin_spawn_egg": "僵尸疣猪兽刷怪蛋",
    "axolotl_spawn_egg": "美西螈刷怪蛋", "goat_spawn_egg": "山羊刷怪蛋",
    "frog_spawn_egg": "青蛙刷怪蛋", "tadpole_spawn_egg": "蝌蚪刷怪蛋",
    "allay_spawn_egg": "悦灵刷怪蛋", "warden_spawn_egg": "监守者刷怪蛋",
    "sniffer_spawn_egg": "嗅探兽刷怪蛋", "camel_spawn_egg": "骆驼刷怪蛋",
    "breeze_spawn_egg": "旋风人刷怪蛋", "armadillo_spawn_egg": "犰狳刷怪蛋",
    "creaking_spawn_egg": "嘎枝刷怪蛋", "happy_ghast_spawn_egg": "快乐恶魂刷怪蛋",
    "iron_golem_spawn_egg": "铁傀儡刷怪蛋", "snow_golem_spawn_egg": "雪傀儡刷怪蛋",
    "ender_dragon_spawn_egg": "末影龙刷怪蛋", "wither_spawn_egg": "凋灵刷怪蛋",
    "npc_spawn_egg": "NPC刷怪蛋", "agent_spawn_egg": "智能体刷怪蛋",
    # === 方块(物品形式) ===
    "stone": "石头", "cobblestone": "圆石", "dirt": "泥土", "grass_block": "草方块",
    "sand": "沙子", "red_sand": "红沙", "gravel": "沙砾", "clay": "黏土块",
    "obsidian": "黑曜石", "crying_obsidian": "哭泣的黑曜石",
    "bedrock": "基岩", "netherrack": "下界岩", "soul_sand": "灵魂沙",
    "soul_soil": "灵魂土", "end_stone": "末地石", "basalt": "玄武岩",
    "blackstone": "黑石", "magma": "岩浆块", "glowstone": "荧石",
    "sea_lantern": "海晶灯", "sponge": "海绵", "wet_sponge": "湿海绵",
    "ice": "冰", "packed_ice": "浮冰", "blue_ice": "蓝冰", "snow": "雪",
    "glass": "玻璃", "tinted_glass": "遮光玻璃",
    # 矿石
    "iron_ore": "铁矿石", "gold_ore": "金矿石", "diamond_ore": "钻石矿石",
    "emerald_ore": "绿宝石矿石", "copper_ore": "铜矿石", "coal_ore": "煤矿石",
    "redstone_ore": "红石矿石", "lapis_ore": "青金石矿石",
    "nether_quartz_ore": "下界石英矿石", "nether_gold_ore": "下界金矿石",
    "ancient_debris": "远古残骸", "deepslate": "深板岩",
    "deepslate_iron_ore": "深层铁矿石", "deepslate_gold_ore": "深层金矿石",
    "deepslate_diamond_ore": "深层钻石矿石", "deepslate_copper_ore": "深层铜矿石",
    "deepslate_coal_ore": "深层煤矿石", "deepslate_redstone_ore": "深层红石矿石",
    "deepslate_lapis_ore": "深层青金石矿石", "deepslate_emerald_ore": "深层绿宝石矿石",
    # 木材
    "oak_log": "橡木原木", "spruce_log": "云杉原木", "birch_log": "白桦原木",
    "jungle_log": "丛林原木", "acacia_log": "金合欢原木", "dark_oak_log": "深色橡木原木",
    "mangrove_log": "红树原木", "cherry_log": "樱花原木", "pale_oak_log": "苍白橡木原木",
    "crimson_stem": "绯红菌柄", "warped_stem": "诡异菌柄",
    "stripped_oak_log": "去皮橡木原木", "stripped_spruce_log": "去皮云杉原木",
    "stripped_birch_log": "去皮白桦原木", "stripped_jungle_log": "去皮丛林原木",
    "stripped_acacia_log": "去皮金合欢原木", "stripped_dark_oak_log": "去皮深色橡木原木",
    "oak_planks": "橡木板", "spruce_planks": "云杉木板", "birch_planks": "白桦木板",
    "jungle_planks": "丛林木板", "acacia_planks": "金合欢木板", "dark_oak_planks": "深色橡木板",
    "mangrove_planks": "红树木板", "cherry_planks": "樱花木板", "pale_oak_planks": "苍白橡木板",
    "crimson_planks": "绯红木板", "warped_planks": "诡异木板", "bamboo_planks": "竹板",
    # 建筑方块
    "sandstone": "砂岩", "red_sandstone": "红砂岩", "stone_bricks": "石砖",
    "mossy_cobblestone": "苔石", "mossy_stone_bricks": "苔石砖",
    "cracked_stone_bricks": "裂纹石砖", "chiseled_stone_bricks": "錾制石砖",
    "granite": "花岗岩", "diorite": "闪长岩", "andesite": "安山岩",
    "polished_granite": "磨制花岗岩", "polished_diorite": "磨制闪长岩",
    "polished_andesite": "磨制安山岩",
    "prismarine": "海晶石", "prismarine_bricks": "海晶石砖", "dark_prismarine": "暗海晶石",
    "nether_bricks": "下界砖块", "red_nether_bricks": "红色下界砖块",
    "quartz_block": "石英块", "smooth_quartz": "平滑石英块",
    "purpur_block": "紫珀块", "purpur_pillar": "紫珀柱",
    "bricks": "砖块", "terracotta": "陶瓦", "white_terracotta": "白色陶瓦",
    "concrete": "混凝土", "white_concrete": "白色混凝土",
    "gray_concrete": "灰色混凝土", "black_concrete": "黑色混凝土",
    "white_wool": "白色羊毛", "black_wool": "黑色羊毛",
    "oak_leaves": "橡树树叶", "spruce_leaves": "云杉树叶",
    # 红石/功能
    "piston": "活塞", "sticky_piston": "粘性活塞", "observer": "侦测器",
    "dispenser": "发射器", "dropper": "投掷器", "note_block": "音符盒",
    "tnt": "TNT", "lever": "拉杆", "stone_button": "石按钮", "oak_button": "橡木按钮",
    "stone_pressure_plate": "石压力板", "oak_pressure_plate": "橡木压力板",
    "tripwire_hook": "绊线钩", "trapped_chest": "陷阱箱", "daylight_detector": "阳光探测器",
    "target": "标靶", "lightning_rod": "避雷针", "sculk_sensor": "幽匿感测体",
    "sculk_shrieker": "幽匿尖啸体", "sculk_catalyst": "幽匿催发体",
    "rail": "铁轨", "activator_rail": "激活铁轨", "detector_rail": "探测铁轨",
    "powered_rail": "充能铁轨",
    # 装饰
    "torch": "火把", "soul_torch": "灵魂火把", "lantern": "灯笼",
    "soul_lantern": "灵魂灯笼", "chest": "箱子", "ender_chest": "末影箱",
    "crafting_table": "工作台", "furnace": "熔炉", "blast_furnace": "高炉",
    "smoker": "烟熏炉", "barrel": "木桶", "loom": "织布机",
    "smithing_table": "锻造台", "fletching_table": "制箭台", "cartography_table": "制图台",
    "grindstone": "砂轮", "stonecutter": "切石机", "anvil": "铁砧",
    "enchanting_table": "附魔台", "bookshelf": "书架", "jukebox": "唱片机",
    "lectern": "讲台", "composter": "堆肥桶", "beehive": "蜂箱", "bee_nest": "蜂巢",
    "respawn_anchor": "重生锚", "lodestone": "磁石", "conduit": "潮涌核心",
    "beacon": "信标", "bell": "钟",
    # 植物/自然
    "oak_sapling": "橡树树苗", "spruce_sapling": "云杉树苗",
    "birch_sapling": "白桦树苗", "jungle_sapling": "丛林树苗",
    "acacia_sapling": "金合欢树苗", "dark_oak_sapling": "深色橡木树苗",
    "mangrove_propagule": "红树胎生苗", "cherry_sapling": "樱花树苗",
    "bamboo": "竹子", "cactus": "仙人掌", "vine": "藤蔓",
    "lily_pad": "睡莲", "dead_bush": "枯死的灌木",
    "grass": "草", "fern": "蕨", "tall_grass": "高草丛", "large_fern": "大型蕨",
    "dandelion": "蒲公英", "poppy": "虞美人", "blue_orchid": "兰花",
    "allium": "绒球葱", "azure_bluet": "蓝花美耳草", "tulip": "郁金香",
    "oxeye_daisy": "滨菊", "cornflower": "矢车菊", "lily_of_the_valley": "铃兰",
    "wither_rose": "凋零玫瑰", "sunflower": "向日葵", "lilac": "丁香",
    "rose_bush": "玫瑰丛", "peony": "牡丹", "pitcher_plant": "瓶子草",
    "torchflower": "火把花", "brown_mushroom": "棕色蘑菇", "red_mushroom": "红色蘑菇",
    "crimson_fungus": "绯红菌", "warped_fungus": "诡异菌",
    "sea_pickle": "海泡菜", "seagrass": "海草", "kelp": "海带",
    # 其他常见
    "cobweb": "蜘蛛网", "moss_block": "苔藓块", "moss_carpet": "苔藓地毯",
    "calcite": "方解石", "tuff": "凝灰岩", "dripstone_block": "滴水石块",
    "pointed_dripstone": "滴水石锥", "amethyst_block": "紫水晶块",
    "budding_amethyst": "紫水晶母岩", "copper_block": "铜块",
    "raw_iron_block": "粗铁块", "raw_gold_block": "粗金块", "raw_copper_block": "粗铜块",
    "iron_block": "铁块", "gold_block": "金块", "diamond_block": "钻石块",
    "emerald_block": "绿宝石块", "netherite_block": "下界合金块",
    "coal_block": "煤炭块", "redstone_block": "红石块", "lapis_block": "青金石块",
    "slime_block": "黏液块", "honey_block": "蜂蜜块",
    "scaffolding": "脚手架", "ladder": "梯子", "snow_layer": "雪层",
    "hay_block": "干草块", "dried_kelp_block": "干海带块",
    "bone_block": "骨块", "shulker_box": "潜影盒",
    "undyed_shulker_box": "潜影盒(无色)",
    "white_shulker_box": "白色潜影盒", "black_shulker_box": "黑色潜影盒",
    # 珊瑚
    "tube_coral": "管珊瑚", "brain_coral": "脑纹珊瑚",
    "bubble_coral": "气泡珊瑚", "fire_coral": "火珊瑚", "horn_coral": "鹿角珊瑚",
    "dead_tube_coral": "失活的管珊瑚", "dead_brain_coral": "失活的脑纹珊瑚",
    "dead_bubble_coral": "失活的气泡珊瑚", "dead_fire_coral": "失活的火珊瑚",
    "dead_horn_coral": "失活的鹿角珊瑚",
    # 活板门/按钮/压力板/栅栏/栅栏门
    "oak_trapdoor": "橡木活板门", "spruce_trapdoor": "云杉活板门",
    "birch_trapdoor": "白桦活板门", "jungle_trapdoor": "丛林活板门",
    "acacia_trapdoor": "金合欢活板门", "dark_oak_trapdoor": "深色橡木活板门",
    "mangrove_trapdoor": "红树活板门", "cherry_trapdoor": "樱花活板门",
    "pale_oak_trapdoor": "苍白橡木活板门", "bamboo_trapdoor": "竹活板门",
    "crimson_trapdoor": "绯红活板门", "warped_trapdoor": "诡异活板门",
    "iron_trapdoor": "铁活板门", "copper_trapdoor": "铜活板门",
    "oak_button": "橡木按钮", "spruce_button": "云杉按钮", "birch_button": "白桦按钮",
    "jungle_button": "丛林按钮", "acacia_button": "金合欢按钮", "dark_oak_button": "深色橡木按钮",
    "mangrove_button": "红树按钮", "cherry_button": "樱花按钮", "pale_oak_button": "苍白橡木按钮",
    "bamboo_button": "竹按钮", "crimson_button": "绯红按钮", "warped_button": "诡异按钮",
    "stone_button": "石按钮", "polished_blackstone_button": "磨制黑石按钮",
    "oak_pressure_plate": "橡木压力板", "spruce_pressure_plate": "云杉压力板",
    "birch_pressure_plate": "白桦压力板", "jungle_pressure_plate": "丛林压力板",
    "acacia_pressure_plate": "金合欢压力板", "dark_oak_pressure_plate": "深色橡木压力板",
    "mangrove_pressure_plate": "红树压力板", "cherry_pressure_plate": "樱花压力板",
    "pale_oak_pressure_plate": "苍白橡木压力板", "bamboo_pressure_plate": "竹压力板",
    "crimson_pressure_plate": "绯红压力板", "warped_pressure_plate": "诡异压力板",
    "stone_pressure_plate": "石压力板", "light_weighted_pressure_plate": "轻质测重压力板",
    "heavy_weighted_pressure_plate": "重质测重压力板",
    "polished_blackstone_pressure_plate": "磨制黑石压力板",
    "oak_fence": "橡木栅栏", "spruce_fence": "云杉栅栏", "birch_fence": "白桦栅栏",
    "jungle_fence": "丛林栅栏", "acacia_fence": "金合欢栅栏", "dark_oak_fence": "深色橡木栅栏",
    "mangrove_fence": "红树栅栏", "cherry_fence": "樱花栅栏", "pale_oak_fence": "苍白橡木栅栏",
    "bamboo_fence": "竹栅栏", "crimson_fence": "绯红栅栏", "warped_fence": "诡异栅栏",
    "nether_brick_fence": "下界砖栅栏",
    "oak_fence_gate": "橡木栅栏门", "spruce_fence_gate": "云杉栅栏门",
    "birch_fence_gate": "白桦栅栏门", "jungle_fence_gate": "丛林栅栏门",
    "acacia_fence_gate": "金合欢栅栏门", "dark_oak_fence_gate": "深色橡木栅栏门",
    "mangrove_fence_gate": "红树栅栏门", "cherry_fence_gate": "樱花栅栏门",
    "pale_oak_fence_gate": "苍白橡木栅栏门", "bamboo_fence_gate": "竹栅栏门",
    "crimson_fence_gate": "绯红栅栏门", "warped_fence_gate": "诡异栅栏门",
    # 楼梯/半砖
    "oak_stairs": "橡木楼梯", "spruce_stairs": "云杉楼梯", "birch_stairs": "白桦楼梯",
    "jungle_stairs": "丛林楼梯", "acacia_stairs": "金合欢楼梯", "dark_oak_stairs": "深色橡木楼梯",
    "mangrove_stairs": "红树楼梯", "cherry_stairs": "樱花楼梯", "pale_oak_stairs": "苍白橡木楼梯",
    "bamboo_stairs": "竹楼梯", "crimson_stairs": "绯红楼梯", "warped_stairs": "诡异楼梯",
    "stone_stairs": "石楼梯", "cobblestone_stairs": "圆石楼梯",
    "stone_brick_stairs": "石砖楼梯", "brick_stairs": "砖楼梯",
    "sandstone_stairs": "砂岩楼梯", "quartz_stairs": "石英楼梯",
    "nether_brick_stairs": "下界砖楼梯", "purpur_stairs": "紫珀楼梯",
    "oak_slab": "橡木台阶", "spruce_slab": "云杉台阶", "birch_slab": "白桦台阶",
    "jungle_slab": "丛林台阶", "acacia_slab": "金合欢台阶", "dark_oak_slab": "深色橡木台阶",
    "mangrove_slab": "红树台阶", "cherry_slab": "樱花台阶", "pale_oak_slab": "苍白橡木台阶",
    "bamboo_slab": "竹台阶", "crimson_slab": "绯红台阶", "warped_slab": "诡异台阶",
    "stone_slab": "石台阶", "cobblestone_slab": "圆石台阶",
    "stone_brick_slab": "石砖台阶", "brick_slab": "砖台阶",
    "sandstone_slab": "砂岩台阶", "quartz_slab": "石英台阶",
    # 墙
    "cobblestone_wall": "圆石墙", "stone_brick_wall": "石砖墙",
    "brick_wall": "砖墙", "sandstone_wall": "砂岩墙",
    "mossy_cobblestone_wall": "苔石墙", "mossy_stone_brick_wall": "苔石砖墙",
    # 地毯/玻璃板
    "white_carpet": "白色地毯", "black_carpet": "黑色地毯",
    "gray_carpet": "灰色地毯", "red_carpet": "红色地毯",
    "glass_pane": "玻璃板", "iron_bars": "铁栏杆",
    # 更多方块
    "podzol": "灰化土", "mycelium": "菌丝", "coarse_dirt": "砂土",
    "rooted_dirt": "缠根泥土", "mud": "泥巴", "packed_mud": "泥坯",
    "mud_bricks": "泥砖", "mud_brick_stairs": "泥砖楼梯", "mud_brick_slab": "泥砖台阶",
    "farmland": "耕地", "dirt_path": "土径",
    "gravel": "沙砾", "suspicious_gravel": "可疑的沙砾", "suspicious_sand": "可疑的沙子",
    "ochre_froglight": "赭黄蛙明灯", "pearlescent_froglight": "珠光蛙明灯",
    "verdant_froglight": "翠绿蛙明灯",
    "mangrove_roots": "红树根", "muddy_mangrove_roots": "沾泥的红树根",
    "azalea": "杜鹃花丛", "flowering_azalea": "盛开的杜鹃花丛",
    "spore_blossom": "孢子花", "big_dripleaf": "大型垂滴叶", "small_dripleaf": "小型垂滴叶",
    "glow_lichen": "发光地衣", "hanging_roots": "垂根",
    "sculk": "幽匿块", "sculk_vein": "幽匿脉络",
    "redstone_lamp": "红石灯", "redstone_torch": "红石火把",
    "dropper": "投掷器", "dispenser": "发射器", "observer": "侦测器",
    "piston": "活塞", "sticky_piston": "粘性活塞",
    "note_block": "音符盒", "jukebox": "唱片机",
    "enchanting_table": "附魔台", "anvil": "铁砧",
    "chipped_anvil": "开裂的铁砧", "damaged_anvil": "损坏的铁砧",
    "end_rod": "末地烛", "lightning_rod": "避雷针",
    "grindstone": "砂轮", "stonecutter": "切石机", "loom": "织布机",
    "fletching_table": "制箭台", "smithing_table": "锻造台", "cartography_table": "制图台",
    "composter": "堆肥桶", "barrel": "木桶", "smoker": "烟熏炉",
    "blast_furnace": "高炉", "furnace": "熔炉", "beehive": "蜂箱",
    "bee_nest": "蜂巢", "respawn_anchor": "重生锚", "lodestone": "磁石",
    "conduit": "潮涌核心", "beacon": "信标", "bell": "钟",
    "lantern": "灯笼", "soul_lantern": "灵魂灯笼",
    "torch": "火把", "soul_torch": "灵魂火把",
    "candle": "蜡烛", "white_candle": "白色蜡烛",
    "scaffolding": "脚手架", "ladder": "梯子",
    "snow": "雪块", "snow_layer": "雪层",
    "lectern": "讲台", "bookshelf": "书架",
    "loom": "织布机", "brewing_stand": "酿造台", "cauldron": "炼药锅",
    # 更多混凝土/陶瓦/羊毛颜色
    "orange_concrete": "橙色混凝土", "magenta_concrete": "品红色混凝土",
    "light_blue_concrete": "淡蓝色混凝土", "yellow_concrete": "黄色混凝土",
    "lime_concrete": "黄绿色混凝土", "pink_concrete": "粉红色混凝土",
    "gray_concrete": "灰色混凝土", "light_gray_concrete": "淡灰色混凝土",
    "cyan_concrete": "青色混凝土", "purple_concrete": "紫色混凝土",
    "blue_concrete": "蓝色混凝土", "brown_concrete": "棕色混凝土",
    "green_concrete": "绿色混凝土", "red_concrete": "红色混凝土",
    "orange_wool": "橙色羊毛", "magenta_wool": "品红色羊毛",
    "light_blue_wool": "淡蓝色羊毛", "yellow_wool": "黄色羊毛",
    "lime_wool": "黄绿色羊毛", "pink_wool": "粉红色羊毛",
    "gray_wool": "灰色羊毛", "light_gray_wool": "淡灰色羊毛",
    "cyan_wool": "青色羊毛", "purple_wool": "紫色羊毛",
    "blue_wool": "蓝色羊毛", "brown_wool": "棕色羊毛",
    "green_wool": "绿色羊毛", "red_wool": "红色羊毛",
    # 铜/切制铜系列
    "cut_copper": "切制铜块", "exposed_copper": "斑驳的铜块",
    "weathered_copper": "锈蚀的铜块", "oxidized_copper": "氧化的铜块",
    "waxed_copper_block": "涂蜡铜块", "cut_copper_stairs": "切制铜楼梯",
    "cut_copper_slab": "切制铜台阶",
    # 下界木头系列
    "crimson_hyphae": "绯红菌核", "warped_hyphae": "诡异菌核",
    "stripped_crimson_hyphae": "去皮绯红菌核", "stripped_warped_hyphae": "去皮诡异菌核",
    "stripped_crimson_stem": "去皮绯红菌柄", "stripped_warped_stem": "去皮诡异菌柄",
    "crimson_nylium": "绯红菌岩", "warped_nylium": "诡异菌岩",
    "shroomlight": "菌光体", "weeping_vines": "垂泪藤", "twisting_vines": "缠怨藤",
    # 末地
    "purpur_block": "紫珀块", "purpur_pillar": "紫珀柱",
    "purpur_stairs": "紫珀楼梯", "purpur_slab": "紫珀台阶",
    "end_stone_bricks": "末地石砖",
    # 矿物块
    "coal_block": "煤炭块", "iron_block": "铁块", "gold_block": "金块",
    "diamond_block": "钻石块", "emerald_block": "绿宝石块",
    "netherite_block": "下界合金块", "redstone_block": "红石块",
    "lapis_block": "青金石块", "copper_block": "铜块",
    "raw_iron_block": "粗铁块", "raw_gold_block": "粗金块", "raw_copper_block": "粗铜块",
    "quartz_block": "石英块", "quartz_bricks": "石英砖", "smooth_quartz": "平滑石英块",
    "amethyst_block": "紫水晶块", "budding_amethyst": "紫水晶母岩",
    # 下界合金升级
    "netherite_upgrade_smithing_template": "下界合金升级锻造模板",
}
